//
// Autogenerated by Thrift Compiler (0.13.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');


var ttypes = module.exports = {};
ttypes.fb_status = {
  'DEAD' : 0,
  'STARTING' : 1,
  'ALIVE' : 2,
  'STOPPING' : 3,
  'STOPPED' : 4,
  'WARNING' : 5
};
