/** Declaration file generated by dts-gen */

export function CreateClient(host: any, port: any, authType: any, params: any, callback: any): any;

export namespace CreateClient {
    function apply(p0: any, p1: any): any;

    function bind(p0: any): any;

    function call(p0: any): any;

    function toString(): any;

    namespace apply {
        // Circular reference from hive_metastore_http_client.CreateClient.apply
        const apply: any;

        function bind(p0: any): any;

        function call(p0: any): any;

        function toString(): any;

        namespace bind {
            // Circular reference from hive_metastore_http_client.CreateClient.apply.bind
            const apply: any;

            // Circular reference from hive_metastore_http_client.CreateClient.apply.bind
            const bind: any;

            function call(p0: any): any;

            function toString(): any;

            namespace call {
                // Circular reference from hive_metastore_http_client.CreateClient.apply.bind.call
                const apply: any;

                // Circular reference from hive_metastore_http_client.CreateClient.apply.bind.call
                const bind: any;

                // Circular reference from hive_metastore_http_client.CreateClient.apply.bind.call
                const call: any;

                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.apply.bind.call
                const toString: any;

            }

            namespace toString {
                // Circular reference from hive_metastore_http_client.CreateClient.apply.bind.toString
                const apply: any;

                // Circular reference from hive_metastore_http_client.CreateClient.apply.bind.toString
                const bind: any;

                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.apply.bind.toString
                const call: any;

                // Circular reference from hive_metastore_http_client.CreateClient.apply.bind.toString
                const toString: any;

            }

        }

        namespace call {
            // Circular reference from hive_metastore_http_client.CreateClient.apply.call
            const apply: any;

            // Circular reference from hive_metastore_http_client.CreateClient.apply.call
            const call: any;

            function bind(p0: any): any;

            function toString(): any;

            namespace bind {
                // Circular reference from hive_metastore_http_client.CreateClient.apply.call.bind
                const apply: any;

                // Circular reference from hive_metastore_http_client.CreateClient.apply.call.bind
                const bind: any;

                // Circular reference from hive_metastore_http_client.CreateClient.apply.call.bind
                const call: any;

                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.apply.call.bind
                const toString: any;

            }

            namespace toString {
                // Circular reference from hive_metastore_http_client.CreateClient.apply.call.toString
                const apply: any;

                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.apply.call.toString
                const bind: any;

                // Circular reference from hive_metastore_http_client.CreateClient.apply.call.toString
                const call: any;

                // Circular reference from hive_metastore_http_client.CreateClient.apply.call.toString
                const toString: any;

            }

        }

        namespace toString {
            // Circular reference from hive_metastore_http_client.CreateClient.apply.toString
            const apply: any;

            // Circular reference from hive_metastore_http_client.CreateClient.apply.toString
            const toString: any;

            function bind(p0: any): any;

            function call(p0: any): any;

            namespace bind {
                // Circular reference from hive_metastore_http_client.CreateClient.apply.toString.bind
                const apply: any;

                // Circular reference from hive_metastore_http_client.CreateClient.apply.toString.bind
                const bind: any;

                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.apply.toString.bind
                const call: any;

                // Circular reference from hive_metastore_http_client.CreateClient.apply.toString.bind
                const toString: any;

            }

            namespace call {
                // Circular reference from hive_metastore_http_client.CreateClient.apply.toString.call
                const apply: any;

                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.apply.toString.call
                const bind: any;

                // Circular reference from hive_metastore_http_client.CreateClient.apply.toString.call
                const call: any;

                // Circular reference from hive_metastore_http_client.CreateClient.apply.toString.call
                const toString: any;

            }

        }

    }

    namespace bind {
        // Circular reference from hive_metastore_http_client.CreateClient.bind
        const bind: any;

        function apply(p0: any, p1: any): any;

        function call(p0: any): any;

        function toString(): any;

        namespace apply {
            // Circular reference from hive_metastore_http_client.CreateClient.bind.apply
            const apply: any;

            // Circular reference from hive_metastore_http_client.CreateClient.bind.apply
            const bind: any;

            function call(p0: any): any;

            function toString(): any;

            namespace call {
                // Circular reference from hive_metastore_http_client.CreateClient.bind.apply.call
                const apply: any;

                // Circular reference from hive_metastore_http_client.CreateClient.bind.apply.call
                const bind: any;

                // Circular reference from hive_metastore_http_client.CreateClient.bind.apply.call
                const call: any;

                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.bind.apply.call
                const toString: any;

            }

            namespace toString {
                // Circular reference from hive_metastore_http_client.CreateClient.bind.apply.toString
                const apply: any;

                // Circular reference from hive_metastore_http_client.CreateClient.bind.apply.toString
                const bind: any;

                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.bind.apply.toString
                const call: any;

                // Circular reference from hive_metastore_http_client.CreateClient.bind.apply.toString
                const toString: any;

            }

        }

        namespace call {
            // Circular reference from hive_metastore_http_client.CreateClient.bind.call
            const bind: any;

            // Circular reference from hive_metastore_http_client.CreateClient.bind.call
            const call: any;

            function apply(p0: any, p1: any): any;

            function toString(): any;

            namespace apply {
                // Circular reference from hive_metastore_http_client.CreateClient.bind.call.apply
                const apply: any;

                // Circular reference from hive_metastore_http_client.CreateClient.bind.call.apply
                const bind: any;

                // Circular reference from hive_metastore_http_client.CreateClient.bind.call.apply
                const call: any;

                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.bind.call.apply
                const toString: any;

            }

            namespace toString {
                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.bind.call.toString
                const apply: any;

                // Circular reference from hive_metastore_http_client.CreateClient.bind.call.toString
                const bind: any;

                // Circular reference from hive_metastore_http_client.CreateClient.bind.call.toString
                const call: any;

                // Circular reference from hive_metastore_http_client.CreateClient.bind.call.toString
                const toString: any;

            }

        }

        namespace toString {
            // Circular reference from hive_metastore_http_client.CreateClient.bind.toString
            const bind: any;

            // Circular reference from hive_metastore_http_client.CreateClient.bind.toString
            const toString: any;

            function apply(p0: any, p1: any): any;

            function call(p0: any): any;

            namespace apply {
                // Circular reference from hive_metastore_http_client.CreateClient.bind.toString.apply
                const apply: any;

                // Circular reference from hive_metastore_http_client.CreateClient.bind.toString.apply
                const bind: any;

                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.bind.toString.apply
                const call: any;

                // Circular reference from hive_metastore_http_client.CreateClient.bind.toString.apply
                const toString: any;

            }

            namespace call {
                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.bind.toString.call
                const apply: any;

                // Circular reference from hive_metastore_http_client.CreateClient.bind.toString.call
                const bind: any;

                // Circular reference from hive_metastore_http_client.CreateClient.bind.toString.call
                const call: any;

                // Circular reference from hive_metastore_http_client.CreateClient.bind.toString.call
                const toString: any;

            }

        }

    }

    namespace call {
        // Circular reference from hive_metastore_http_client.CreateClient.call
        const call: any;

        function apply(p0: any, p1: any): any;

        function bind(p0: any): any;

        function toString(): any;

        namespace apply {
            // Circular reference from hive_metastore_http_client.CreateClient.call.apply
            const apply: any;

            // Circular reference from hive_metastore_http_client.CreateClient.call.apply
            const call: any;

            function bind(p0: any): any;

            function toString(): any;

            namespace bind {
                // Circular reference from hive_metastore_http_client.CreateClient.call.apply.bind
                const apply: any;

                // Circular reference from hive_metastore_http_client.CreateClient.call.apply.bind
                const bind: any;

                // Circular reference from hive_metastore_http_client.CreateClient.call.apply.bind
                const call: any;

                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.call.apply.bind
                const toString: any;

            }

            namespace toString {
                // Circular reference from hive_metastore_http_client.CreateClient.call.apply.toString
                const apply: any;

                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.call.apply.toString
                const bind: any;

                // Circular reference from hive_metastore_http_client.CreateClient.call.apply.toString
                const call: any;

                // Circular reference from hive_metastore_http_client.CreateClient.call.apply.toString
                const toString: any;

            }

        }

        namespace bind {
            // Circular reference from hive_metastore_http_client.CreateClient.call.bind
            const bind: any;

            // Circular reference from hive_metastore_http_client.CreateClient.call.bind
            const call: any;

            function apply(p0: any, p1: any): any;

            function toString(): any;

            namespace apply {
                // Circular reference from hive_metastore_http_client.CreateClient.call.bind.apply
                const apply: any;

                // Circular reference from hive_metastore_http_client.CreateClient.call.bind.apply
                const bind: any;

                // Circular reference from hive_metastore_http_client.CreateClient.call.bind.apply
                const call: any;

                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.call.bind.apply
                const toString: any;

            }

            namespace toString {
                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.call.bind.toString
                const apply: any;

                // Circular reference from hive_metastore_http_client.CreateClient.call.bind.toString
                const bind: any;

                // Circular reference from hive_metastore_http_client.CreateClient.call.bind.toString
                const call: any;

                // Circular reference from hive_metastore_http_client.CreateClient.call.bind.toString
                const toString: any;

            }

        }

        namespace toString {
            // Circular reference from hive_metastore_http_client.CreateClient.call.toString
            const call: any;

            // Circular reference from hive_metastore_http_client.CreateClient.call.toString
            const toString: any;

            function apply(p0: any, p1: any): any;

            function bind(p0: any): any;

            namespace apply {
                // Circular reference from hive_metastore_http_client.CreateClient.call.toString.apply
                const apply: any;

                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.call.toString.apply
                const bind: any;

                // Circular reference from hive_metastore_http_client.CreateClient.call.toString.apply
                const call: any;

                // Circular reference from hive_metastore_http_client.CreateClient.call.toString.apply
                const toString: any;

            }

            namespace bind {
                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.call.toString.bind
                const apply: any;

                // Circular reference from hive_metastore_http_client.CreateClient.call.toString.bind
                const bind: any;

                // Circular reference from hive_metastore_http_client.CreateClient.call.toString.bind
                const call: any;

                // Circular reference from hive_metastore_http_client.CreateClient.call.toString.bind
                const toString: any;

            }

        }

    }

    namespace toString {
        // Circular reference from hive_metastore_http_client.CreateClient.toString
        const toString: any;

        function apply(p0: any, p1: any): any;

        function bind(p0: any): any;

        function call(p0: any): any;

        namespace apply {
            // Circular reference from hive_metastore_http_client.CreateClient.toString.apply
            const apply: any;

            // Circular reference from hive_metastore_http_client.CreateClient.toString.apply
            const toString: any;

            function bind(p0: any): any;

            function call(p0: any): any;

            namespace bind {
                // Circular reference from hive_metastore_http_client.CreateClient.toString.apply.bind
                const apply: any;

                // Circular reference from hive_metastore_http_client.CreateClient.toString.apply.bind
                const bind: any;

                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.toString.apply.bind
                const call: any;

                // Circular reference from hive_metastore_http_client.CreateClient.toString.apply.bind
                const toString: any;

            }

            namespace call {
                // Circular reference from hive_metastore_http_client.CreateClient.toString.apply.call
                const apply: any;

                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.toString.apply.call
                const bind: any;

                // Circular reference from hive_metastore_http_client.CreateClient.toString.apply.call
                const call: any;

                // Circular reference from hive_metastore_http_client.CreateClient.toString.apply.call
                const toString: any;

            }

        }

        namespace bind {
            // Circular reference from hive_metastore_http_client.CreateClient.toString.bind
            const bind: any;

            // Circular reference from hive_metastore_http_client.CreateClient.toString.bind
            const toString: any;

            function apply(p0: any, p1: any): any;

            function call(p0: any): any;

            namespace apply {
                // Circular reference from hive_metastore_http_client.CreateClient.toString.bind.apply
                const apply: any;

                // Circular reference from hive_metastore_http_client.CreateClient.toString.bind.apply
                const bind: any;

                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.toString.bind.apply
                const call: any;

                // Circular reference from hive_metastore_http_client.CreateClient.toString.bind.apply
                const toString: any;

            }

            namespace call {
                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.toString.bind.call
                const apply: any;

                // Circular reference from hive_metastore_http_client.CreateClient.toString.bind.call
                const bind: any;

                // Circular reference from hive_metastore_http_client.CreateClient.toString.bind.call
                const call: any;

                // Circular reference from hive_metastore_http_client.CreateClient.toString.bind.call
                const toString: any;

            }

        }

        namespace call {
            // Circular reference from hive_metastore_http_client.CreateClient.toString.call
            const call: any;

            // Circular reference from hive_metastore_http_client.CreateClient.toString.call
            const toString: any;

            function apply(p0: any, p1: any): any;

            function bind(p0: any): any;

            namespace apply {
                // Circular reference from hive_metastore_http_client.CreateClient.toString.call.apply
                const apply: any;

                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.toString.call.apply
                const bind: any;

                // Circular reference from hive_metastore_http_client.CreateClient.toString.call.apply
                const call: any;

                // Circular reference from hive_metastore_http_client.CreateClient.toString.call.apply
                const toString: any;

            }

            namespace bind {
                // Too-deep object hierarchy from hive_metastore_http_client.CreateClient.toString.call.bind
                const apply: any;

                // Circular reference from hive_metastore_http_client.CreateClient.toString.call.bind
                const bind: any;

                // Circular reference from hive_metastore_http_client.CreateClient.toString.call.bind
                const call: any;

                // Circular reference from hive_metastore_http_client.CreateClient.toString.call.bind
                const toString: any;

            }

        }

    }

}

export namespace DefaultOptions {
    class protocol {
        constructor(trans: any);

        flush(): any;

        getTransport(): any;

        readBinary(): any;

        readBool(): any;

        readByte(): any;

        readDouble(): any;

        readFieldBegin(): any;

        readFieldEnd(): void;

        readI16(): any;

        readI32(f: any): any;

        readI64(): any;

        readListBegin(): any;

        readListEnd(): void;

        readMapBegin(): any;

        readMapEnd(): void;

        readMessageBegin(): any;

        readMessageEnd(): void;

        readSetBegin(): any;

        readSetEnd(): any;

        readString(): any;

        readStructBegin(): any;

        readStructEnd(): void;

        readValue(f: any): any;

        skip(type: any): void;

        writeBinary(arg: any): void;

        writeBool(bool: any): void;

        writeByte(byte: any): void;

        writeDouble(dub: any): void;

        writeFieldBegin(name: any, fieldType: any, fieldId: any): void;

        writeFieldEnd(): void;

        writeFieldStop(): void;

        writeI16(i16: any): void;

        writeI32(i32: any): void;

        writeI64(i64: any): void;

        writeListBegin(elemType: any, size: any): void;

        writeListEnd(): void;

        writeMapBegin(keyType: any, valType: any, size: any): void;

        writeMapEnd(): void;

        writeMessageBegin(name: any, messageType: any, seqid: any): void;

        writeMessageEnd(): void;

        writeSetBegin(elemType: any, size: any): void;

        writeSetEnd(): void;

        writeString(arg: any): void;

        writeStructBegin(name: any): void;

        writeStructEnd(): void;

        writeToTransportIfStackIsFlushable(): void;

        static RType: {
            dbl: number;
            i16: number;
            i32: number;
            i64: number;
            i8: number;
            lst: number;
            map: number;
            rec: number;
            set: number;
            str: number;
            tf: number;
        };

        static Type: {
            "10": string;
            "11": string;
            "12": string;
            "13": string;
            "14": string;
            "15": string;
            "2": string;
            "3": string;
            "4": string;
            "6": string;
            "8": string;
        };

        static Version: number;

        static apply(p0: any, p1: any): any;

        static bind(p0: any): any;

        static call(p0: any): any;

        static toString(): any;

    }

    class transport {
        constructor(buffer: any, callback: any);

        borrow(): any;

        close(): void;

        commitPosition(): void;

        consume(bytesConsumed: any): void;

        ensureAvailable(len: any): void;

        flush(): void;

        isOpen(): any;

        open(): void;

        read(len: any): any;

        readByte(): any;

        readDouble(): any;

        readI16(): any;

        readI32(): any;

        readString(len: any): any;

        reset(): void;

        rollbackPosition(): void;

        setCurrSeqId(seqid: any): void;

        write(buf: any): void;

        static apply(p0: any, p1: any): any;

        static bind(p0: any): any;

        static call(p0: any): any;

        static receiver(callback: any, seqid: any): any;

        static toString(): any;

    }

    const headers: {
        Connection: string;
    };

    const https: boolean;

    const path: string;

    namespace protocol {
        namespace apply {
            // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.apply
            const apply: any;

            function bind(p0: any): any;

            function call(p0: any): any;

            function toString(): any;

            namespace bind {
                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.apply.bind
                const apply: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.apply.bind
                const bind: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.apply.bind
                const call: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.apply.bind
                const toString: any;

            }

            namespace call {
                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.apply.call
                const apply: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.apply.call
                const bind: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.apply.call
                const call: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.apply.call
                const toString: any;

            }

            namespace toString {
                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.apply.toString
                const apply: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.apply.toString
                const bind: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.apply.toString
                const call: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.apply.toString
                const toString: any;

            }

        }

        namespace bind {
            // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.bind
            const bind: any;

            function apply(p0: any, p1: any): any;

            function call(p0: any): any;

            function toString(): any;

            namespace apply {
                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.bind.apply
                const apply: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.bind.apply
                const bind: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.bind.apply
                const call: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.bind.apply
                const toString: any;

            }

            namespace call {
                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.bind.call
                const apply: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.bind.call
                const bind: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.bind.call
                const call: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.bind.call
                const toString: any;

            }

            namespace toString {
                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.bind.toString
                const apply: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.bind.toString
                const bind: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.bind.toString
                const call: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.bind.toString
                const toString: any;

            }

        }

        namespace call {
            // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.call
            const call: any;

            function apply(p0: any, p1: any): any;

            function bind(p0: any): any;

            function toString(): any;

            namespace apply {
                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.call.apply
                const apply: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.call.apply
                const bind: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.call.apply
                const call: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.call.apply
                const toString: any;

            }

            namespace bind {
                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.call.bind
                const apply: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.call.bind
                const bind: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.call.bind
                const call: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.call.bind
                const toString: any;

            }

            namespace toString {
                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.call.toString
                const apply: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.call.toString
                const bind: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.call.toString
                const call: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.call.toString
                const toString: any;

            }

        }

        namespace toString {
            // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.toString
            const toString: any;

            function apply(p0: any, p1: any): any;

            function bind(p0: any): any;

            function call(p0: any): any;

            namespace apply {
                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.toString.apply
                const apply: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.toString.apply
                const bind: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.toString.apply
                const call: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.toString.apply
                const toString: any;

            }

            namespace bind {
                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.toString.bind
                const apply: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.toString.bind
                const bind: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.toString.bind
                const call: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.toString.bind
                const toString: any;

            }

            namespace call {
                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.toString.call
                const apply: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.protocol.toString.call
                const bind: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.toString.call
                const call: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.protocol.toString.call
                const toString: any;

            }

        }

    }

    namespace transport {
        namespace apply {
            // Circular reference from hive_metastore_http_client.DefaultOptions.transport.apply
            const apply: any;

            function bind(p0: any): any;

            function call(p0: any): any;

            function toString(): any;

            namespace bind {
                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.apply.bind
                const apply: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.apply.bind
                const bind: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.apply.bind
                const call: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.apply.bind
                const toString: any;

            }

            namespace call {
                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.apply.call
                const apply: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.apply.call
                const bind: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.apply.call
                const call: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.apply.call
                const toString: any;

            }

            namespace toString {
                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.apply.toString
                const apply: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.apply.toString
                const bind: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.apply.toString
                const call: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.apply.toString
                const toString: any;

            }

        }

        namespace bind {
            // Circular reference from hive_metastore_http_client.DefaultOptions.transport.bind
            const bind: any;

            function apply(p0: any, p1: any): any;

            function call(p0: any): any;

            function toString(): any;

            namespace apply {
                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.bind.apply
                const apply: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.bind.apply
                const bind: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.bind.apply
                const call: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.bind.apply
                const toString: any;

            }

            namespace call {
                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.bind.call
                const apply: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.bind.call
                const bind: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.bind.call
                const call: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.bind.call
                const toString: any;

            }

            namespace toString {
                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.bind.toString
                const apply: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.bind.toString
                const bind: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.bind.toString
                const call: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.bind.toString
                const toString: any;

            }

        }

        namespace call {
            // Circular reference from hive_metastore_http_client.DefaultOptions.transport.call
            const call: any;

            function apply(p0: any, p1: any): any;

            function bind(p0: any): any;

            function toString(): any;

            namespace apply {
                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.call.apply
                const apply: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.call.apply
                const bind: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.call.apply
                const call: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.call.apply
                const toString: any;

            }

            namespace bind {
                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.call.bind
                const apply: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.call.bind
                const bind: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.call.bind
                const call: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.call.bind
                const toString: any;

            }

            namespace toString {
                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.call.toString
                const apply: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.call.toString
                const bind: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.call.toString
                const call: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.call.toString
                const toString: any;

            }

        }

        namespace receiver {
            function apply(p0: any, p1: any): any;

            function bind(p0: any): any;

            function call(p0: any): any;

            function toString(): any;

            namespace apply {
                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.receiver.apply
                const apply: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.receiver.apply
                const bind: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.receiver.apply
                const call: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.receiver.apply
                const toString: any;

            }

            namespace bind {
                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.receiver.bind
                const apply: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.receiver.bind
                const bind: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.receiver.bind
                const call: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.receiver.bind
                const toString: any;

            }

            namespace call {
                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.receiver.call
                const apply: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.receiver.call
                const bind: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.receiver.call
                const call: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.receiver.call
                const toString: any;

            }

            namespace toString {
                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.receiver.toString
                const apply: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.receiver.toString
                const bind: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.receiver.toString
                const call: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.receiver.toString
                const toString: any;

            }

        }

        namespace toString {
            // Circular reference from hive_metastore_http_client.DefaultOptions.transport.toString
            const toString: any;

            function apply(p0: any, p1: any): any;

            function bind(p0: any): any;

            function call(p0: any): any;

            namespace apply {
                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.toString.apply
                const apply: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.toString.apply
                const bind: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.toString.apply
                const call: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.toString.apply
                const toString: any;

            }

            namespace bind {
                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.toString.bind
                const apply: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.toString.bind
                const bind: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.toString.bind
                const call: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.toString.bind
                const toString: any;

            }

            namespace call {
                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.toString.call
                const apply: any;

                // Too-deep object hierarchy from hive_metastore_http_client.DefaultOptions.transport.toString.call
                const bind: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.toString.call
                const call: any;

                // Circular reference from hive_metastore_http_client.DefaultOptions.transport.toString.call
                const toString: any;

            }

        }

    }

}

